version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data/db
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  redis-insight:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    environment:
      - REDIS_URI=redis://redis:6379
    volumes:
      - ./volumes/redis-insight:/db
    links:
      - redis